In [4]:
import torch 

In [14]:
TENSOR = torch.rand(2,3, device=None, requires_grad=False, dtype=torch.float64)


In [15]:
tensor_A = torch.rand(3,2, dtype=torch.float)

In [10]:
TENSOR_03 = torch.mm(TENSOR, TENSOR_02)
TENSOR_03

NameError: name 'TENSOR' is not defined

In [16]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix mutliplcation
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[ 1.0348,  0.4592,  0.3892,  0.0690,  0.3858,  0.3514],
        [ 0.9272,  0.3378,  0.3622, -0.0094,  0.4842,  0.3286],
        [ 1.1711,  0.5868,  0.4136,  0.1433,  0.2987,  0.3971]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [30]:
a = torch.rand(2,3, dtype=torch.float32) 
b = torch.rand(3,2, dtype=torch.float32)

In [31]:
c = torch.mm(a,b)
c


tensor([[0.1242, 0.0812],
        [0.6341, 0.3753]])

In [37]:
d = torch.arange(0,110, 10)
d

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [45]:
e = torch.argmin(a)
e


tensor(2)

In [6]:
F = torch.rand(2,4, dtype=torch.float32)


In [7]:
torch.Tensor.type(F, dtype=torch.int64)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])

In [1]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [2]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.66 ms, sys: 3.35 ms, total: 5.01 ms
Wall time: 9.33 ms


tensor(14)

In [3]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 308 µs, sys: 86 µs, total: 394 µs
Wall time: 424 µs


tensor(14)

In [7]:
tensor1 = torch.tensor([2,4,7,8], dtype=torch.float64) 

In [14]:
x = 0 
tensor1=x 

In [17]:
y = torch.stack([x,x,x,x,x], dim=1 ) 

TypeError: expected Tensor as element 0 in argument 0, but got int